development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:e14fdce5ac155c5a7e5dcd950e2f6192@soldierfish.redistogo.com:11452/
  #channel_prefix: workspace_production
